#About units:
#We use the gravitational constant G=6.672E-3,you may modify it to higher accuracy in g_cub or g_sph as you need.
#the space parameters in m
#the density in g/cm3
#the computed uz in mGal
#and the gravity gradient tensors in E

#z axis positive for horizontal downwards,
#which indicates that the points above the ground with negative z. 


#Examples:
#compute the Uz(gz) in point (0.0,0.0,-10.0)
#generated by a cuboid defined by vertexes at (1.0,1.0,1.0) and (2.0,2.0,2.0),density 1.0
#Ux and Uy are not supported by now.
from g_cub import g_cub,G
rho=1.0
g=G*rho*g_cub(0.0,0.0,-10.0,1.0,2.0,1.0,2.0,1.0,2.0,'ux')


#compute the Uxx in point (0.0,0.0,-10.0)
#generate by a sphere with centre (1.0,1.0,1.0) and radius 0.5,density 2.0
#Gravity gradient tensors parameters are:
#uxx,uyy,uzz,uxy,uyz,uzx
from g_sph import g_sph,G
rho=2.0
g=G*rho*g_sph(0.0,0.0,-10.0,1.0,1.0,1.0,0.5,'uxx')
